Repository Riserax/food-hub, pull requests merged in 2020-04, with the labels that each got.

#6 Update readme
  README.md
Labels: documentation

#11 #4 - Initialize project
  .browserslistrc
  .eslintrc.js
  .gitignore
  .prettierrc
  .vscode/settings.json
  babel.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/assets/food-hub-logo.png
  src/assets/logo.png
  src/main.js
  src/store/index.js
Labels: enhancement

#12 #7 Create basic page template with header, body and footer
  src/App.vue
  src/components/cards-container/CardsContainer.vue
  src/components/footer/Footer.vue
  src/components/header/Header.vue
  src/components/slider/Slider.vue
  src/router/index.js
  src/views/Favourites.vue
  src/views/HomePage.vue
Labels: enhancement

#14 Update readme
  README.md
Labels: documentation, enhancement

#15 Header layout with responsive behaviour
  public/index.html
  src/App.vue
  src/assets/ic_account_circle.svg
  src/assets/ic_favorite.svg
  src/assets/ic_history.svg
  src/assets/ic_menu.svg
  src/assets/ic_search.svg
  src/components/header/Header.vue
Labels: enhancement

#32 Cards container
  package.json
  src/assets/recipe-card-no-image.jpg
  src/components/cards-container/CardsContainer.vue
  src/components/recipe-card/RecipeCard.vue
  src/mock/RecipeData.js
  src/views/HomePage.vue
Labels: enhancement

#33 Search area basic layout
  src/App.vue
  src/assets/ic_account_circle.svg
  src/assets/ic_favorite.svg
  src/assets/ic_history.svg
  src/assets/ic_menu.svg
  src/assets/ic_search.svg
  src/components/header/Header.vue
  src/components/header/SearchArea.vue
  src/router/index.js
  src/views/SearchResults.vue
Labels: enhancement

#34 Added services to help getting API calls in
  package-lock.json
  package.json
  src/services/services.js
Labels: API

#36 Searching by ingredients
  src/App.vue
  src/components/header/Header.vue
  src/components/header/SearchArea.vue
Labels: enhancement

#40 Searching actions
  src/components/header/Header.vue
  src/mock/RecipeData.js
  src/services/services.js
  src/store/index.js
  src/views/SearchResults.vue
Labels: enhancement

#41 Recipe details first section (images, action buttons etc.)
  public/index.html
  src/components/recipe/BasicInfo.vue
  src/mock/RecipeData.js
  src/router/index.js
  src/views/Recipe.vue
Labels: enhancement

#42 Sign in sign up modal
  .prettierrc
  public/index.html
  src/App.vue
  src/assets/facebook-logo-icon-transparent.png
  src/components/header/Header.vue
  src/components/sign-in-modal/ModalMode.js
  src/components/sign-in-modal/SignInModal.vue
Labels: enhancement

#43 Added services to keep images
  src/services/services.js
Labels: API, enhancement

#47 Ingredients section in recipe details page
  src/components/recipe/BasicInfo.vue
  src/components/recipe/Ingredients.vue
  src/views/Recipe.vue
Labels: enhancement

#48 #30 - Add general layout for favourites page
  src/views/Favourites.vue
Labels: enhancement

#49 Recipe details directions section implementation
  src/components/recipe/Directions.vue
  src/views/Recipe.vue
Labels: enhancement

#50 console.log() clean-up
  src/components/header/Header.vue
  src/mock/RecipeData.js
Labels: bug

#52 Nutrition facts recipe details section implementation, recipe details full implementation
  src/components/recipe/NutritionFacts.vue
  src/mock/RecipeData.js
  src/views/Recipe.vue
Labels: enhancement

#57 Recipe details page - basic info section header responsiveness bug fixed
  src/components/recipe/BasicInfo.vue
Labels: bug

#56 Firebase login (v7.14) + reposnsivity
  package-lock.json
  package.json
  public/index.html
  src/components/sign-in-modal/SignInModal.vue
  src/main.js
  src/services/services.js
Labels: Firebase

#59 Cards container pagination
  package-lock.json
  package.json
  src/components/cards-container/CardsContainer.vue
  src/mock/RecipeData.js
  src/views/Favourites.vue
  src/views/HomePage.vue
  src/views/SearchResults.vue
Labels: enhancement

#62 Save user data on log in
  package-lock.json
  package.json
  src/components/sign-in-modal/SignInModal.vue
  src/main.js
  src/store/index.js
Labels: API, enhancement

#61 #53 - Catch errors when navigating same page from header
  src/components/header/Header.vue
Labels: bug

#64 Mock requests into real ones
  src/components/header/Header.vue
  src/services/services.js
  src/views/HomePage.vue
  src/views/Recipe.vue
  src/views/SearchResults.vue
Labels: API, enhancement

#66 Fixed wrong number of found recipes
  src/views/SearchResults.vue
Labels: bug

#67 #60 - Change state of header elements if user is logged in
  src/components/header/Header.vue
  src/components/sign-in-modal/SignInModal.vue
  src/main.js
  src/store/index.js
Labels: enhancement

#69 history in firebase, favourites in firebase
  src/components/recipe-card/RecipeCard.vue
  src/components/recipe/BasicInfo.vue
  src/main.js
  src/services/services.js
  src/views/Recipe.vue
Labels: API, Firebase

#77 Random joke generator on profile page
  src/services/services.js
  src/views/Profile.vue
Labels: API, enhancement

#78 History page
  src/components/header/Header.vue
  src/router/index.js
  src/views/History.vue
  src/views/Recipe.vue
Labels: Firebase, enhancement

#81 Email displaying, sign out and delete account buttons implementation
  src/views/Profile.vue
Labels: Firebase, enhancement, help wanted

#83 Button for generating new joke added
  src/views/Profile.vue
Labels: enhancement

#87 Added deploy script
  deploy.sh
  src/services/services.js
  vue.config.js
Labels: enhancement

#88 Bug fix - hide ingredients div in results when no ingredients chosen
  src/views/SearchResults.vue
Labels: bug, checking

#86 Prevent unauthorized routing
  src/router/index.js
  src/views/Favourites.vue
  src/views/History.vue
  src/views/Profile.vue
Labels: bug, enhancement

#99 Reversed history list order
  src/views/History.vue
Labels: enhancement

#100 About page view linked in footer
  src/components/footer/Footer.vue
  src/router/index.js
  src/views/About.vue
Labels: documentation, enhancement

#85 Detecting recipe state and changing icon respectively + ingredients section bugfix
  src/components/recipe/BasicInfo.vue
  src/components/recipe/Ingredients.vue
  src/views/Recipe.vue
Labels: Firebase, bug, enhancement

#96 Carousel slide description opacity changed to decimal
  src/components/carousel/Carousel.vue
Labels: bug

#104 Favourites list order reversed
  src/views/Favourites.vue
Labels: enhancement

#106 About page with project documentation
  src/assets/header_logged_in.png
  src/assets/header_not_logged_in.png
  src/assets/profile_page.png
  src/assets/recipe_details.png
  src/assets/search_area.png
  src/assets/search_area_filled.png
  src/assets/searching_results.png
  src/assets/sign_in_modal.png
  src/assets/start_page.png
  src/views/About.vue
Labels: documentation

#105 Scroll page up when entering recipe details
  src/views/Recipe.vue
Labels: bug, enhancement

#111 Scroll page up when entering about page
  src/views/About.vue
Labels: bug, documentation, enhancement

#91 Create autodeployment script
  .github/workflows/CI_test.yml
Labels: enhancement

#113 Assets organized into subdirectories
  src/assets/about_page/header_logged_in.png
  src/assets/about_page/header_not_logged_in.png
  src/assets/about_page/profile_page.png
  src/assets/about_page/recipe_details.png
  src/assets/about_page/search_area.png
  src/assets/about_page/search_area_filled.png
  src/assets/about_page/searching_results.png
  src/assets/about_page/sign_in_modal.png
  src/assets/about_page/start_page.png
  src/assets/cards_container/recipe-card-no-image.jpg
  src/assets/facebook-logo-icon-transparent.png
  src/assets/homepage/carousel/slide1.jpg
  src/assets/homepage/carousel/slide2.jpg
  src/assets/homepage/carousel/slide3.jpg
  src/assets/homepage/carousel/slide4.jpg
  src/assets/homepage/carousel/slide5.jpg
  src/assets/homepage/food-hub-logo.png
  src/assets/logo.png
  src/assets/profile_page/profile-icon.svg
  src/components/carousel/Carousel.vue
  src/components/header/Header.vue
  src/components/recipe-card/RecipeCard.vue
  src/views/About.vue
  src/views/Profile.vue
Labels: enhancement

#116 Set default card image + fixed searching by name bug
  src/assets/cards_container/recipe-card-no-image.jpg
  src/views/SearchResults.vue
Labels: bug, enhancement

#114 Autofocus on ingredients input + disable adding when input empty
  src/components/header/Header.vue
  src/views/About.vue
Labels: bug, enhancement

#118 Add removing from favourites
  src/components/recipe/BasicInfo.vue
  src/components/sign-in-modal/SignInModal.vue
  src/services/FirebaseServices.js
  src/views/Favourites.vue
  src/views/History.vue
  src/views/Profile.vue
  src/views/Recipe.vue
Labels: Firebase, enhancement

#119 Added loader while searching recipes
  src/components/header/Header.vue
  src/store/index.js
  src/views/SearchResults.vue
Labels: enhancement

#124 Vue-headful component added for setting document titles
  package-lock.json
  package.json
  src/App.vue
  src/views/About.vue
  src/views/Favourites.vue
  src/views/History.vue
  src/views/HomePage.vue
  src/views/Profile.vue
  src/views/Recipe.vue
  src/views/SearchResults.vue
Labels: enhancement

#128 Potential fix for mobile displaying
  src/components/sign-in-modal/SignInModal.vue
Labels: Mobile, bug

#129 Avoid duplicating history and favourites
  src/components/recipe/BasicInfo.vue
  src/services/FirebaseServices.js
  src/views/Recipe.vue
Labels: API, bug

#130 Fix sign up modal for mobile
  src/components/sign-in-modal/SignInModal.vue
Labels: Mobile, bug

#127 Pagination with dynamic result loading for search results
  src/components/cards-container/CardsContainer.vue
  src/services/SpoonacularServices.js
  src/views/SearchResults.vue
Labels: enhancement
