Repository Riserax/food-hub, pull requests merged in 2020-05, with the labels that each got.

#131 Remove unused filter from profile svg
  src/components/header/Header.vue
Labels: bug

#133 Responsivity fixes
  src/assets/cards_container/recipe-card-no-image.jpg
  src/components/recipe/BasicInfo.vue
Labels: bug

#135 Change scroll behaviour on modal toggle
  public/index.html
  src/components/sign-in-modal/SignInModal.vue
Labels: bug

#137 Improve print layout
  src/components/footer/Footer.vue
  src/components/header/Header.vue
  src/components/recipe/BasicInfo.vue
  src/components/recipe/Directions.vue
  src/components/recipe/Ingredients.vue
  src/components/recipe/NutritionFacts.vue
  src/views/Recipe.vue
Labels: enhancement

#138 Ingredients and keywords autocomplete
  src/components/header/Header.vue
  src/services/SpoonacularServices.js
  src/views/SearchResults.vue
Labels: API, enhancement
